# Generated by Django 5.1.2 on 2025-09-17 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=2550)),
                ('location', models.CharField(blank=True, max_length=2550, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('content', models.TextField()),
                ('identity', models.CharField(blank=True, max_length=2550, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teaching',
                'verbose_name_plural': 'Teachings',
                'ordering': ['-created_at'],
            },
        ),
    ]
