# Generated by Django 5.1.2 on 2025-01-31 06:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMassReading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=2555)),
                ('lectionary', models.CharField(max_length=255)),
                ('reading_one', models.CharField(max_length=255)),
                ('reading_one_text', models.TextField()),
                ('psalm', models.CharField(max_length=255)),
                ('responsorial_psalm', models.TextField()),
                ('reading_two', models.CharField(blank=True, max_length=255, null=True)),
                ('reading_two_text', models.TextField(blank=True, null=True)),
                ('alleluia', models.CharField(blank=True, max_length=255, null=True)),
                ('alleluia_text', models.TextField(blank=True, null=True)),
                ('gospel', models.CharField(max_length=255)),
                ('gospel_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Daily Mass Reading',
                'verbose_name_plural': 'Daily Mass Readings',
                'ordering': ['-created_at'],
            },
        ),
    ]
