# Generated by Django 5.1.2 on 2025-02-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymassreading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymassreading',
            name='date',
            field=models.DateField(default='2025-02-14'),
            preserve_default=False,
        ),
    ]
