# Generated by Django 5.1.2 on 2025-02-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailymassreading', '0002_dailymassreading_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymassreading',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Mass Reading', 'verbose_name_plural': 'Daily Mass Readings'},
        ),
    ]
