# Generated by Django 5.1.2 on 2025-02-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailymassreading', '0003_alter_dailymassreading_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymassreading',
            options={'ordering': ['-mass_date'], 'verbose_name': 'Daily Mass Reading', 'verbose_name_plural': 'Daily Mass Readings'},
        ),
        migrations.RenameField(
            model_name='dailymassreading',
            old_name='date',
            new_name='mass_date',
        ),
    ]
