# Generated by Django 5.1.2 on 2025-02-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailymassreading', '0004_alter_dailymassreading_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymassreading',
            options={'ordering': ['-mass_date', '-created_at'], 'verbose_name': 'Daily Mass Reading', 'verbose_name_plural': 'Daily Mass Readings'},
        ),
    ]
