# Generated by Django 5.1.2 on 2024-12-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_deletionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionrequest',
            name='reason',
            field=models.TextField(default='No reason'),
            preserve_default=False,
        ),
    ]
