# Generated by Django 5.1.2 on 2025-01-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', '-created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
