# Generated by Django 5.1.2 on 2024-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
    ]
