# Generated by Django 5.1.2 on 2025-01-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prayer',
            options={'ordering': ['position', '-created_at'], 'verbose_name': 'Prayer', 'verbose_name_plural': 'Prayers'},
        ),
    ]
