# Generated by Django 5.1.2 on 2024-12-04 13:37

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVerse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('verse_text', models.TextField()),
                ('verse_reference', models.CharField(help_text='e.g. John 3:16', max_length=255)),
                ('active_date', models.DateField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='dailyverse')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyverses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Verse',
                'verbose_name_plural': 'Daily Verses',
                'ordering': ['-active_date'],
            },
        ),
    ]
